name: Push Image to Docker Hub
on: workflow_dispatch
jobs:
  backend-feed-api:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: ./udagram-api-feed/
          file: ./udagram-api-feed/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/udagram-api-feed:latest

      - name: verify
        run: echo ${{ steps.docker_build.outputs.digest}}

  
  backend-user-api:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: ./udagram-api-user/
          file: ./udagram-api-user/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/udagram-api-user:latest

      - name: verify
        run: echo ${{ steps.docker_build.outputs.digest}}


  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: ./udagram-reverseproxy/
          file: ./udagram-reverseproxy/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/udagram-reverseproxy:latest

      - name: verify
        run: echo ${{ steps.docker_build.outputs.digest}}


  reverseproxy:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: ./udagram-reverseproxy/
          file: ./udagram-reverseproxy/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/udagram-reverseproxy:latest

      - name: verify
        run: echo ${{ steps.docker_build.outputs.digest}}
